import Navbar from '@/components/Navbar'
import Head from 'next/head'
import styles from '../styles/home.module.css'
import { motion } from "framer-motion"
import { fade, fadeIn, textFadeUp } from '@/pages/utils/motion'
import Link from 'next/link'
import Image from 'next/image'


export default function Home() {
  return (
    <>
      <Head>
        <title>Vemara Solutions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.heroWrapper}>
        <video
          src={"opnsrc.mp4"}
          autoPlay
          playsInline
          muted
          loop
          controls={false}
          className={styles.video}
        />

        <div className={styles.heroContainer}>
          <div className={styles.heroContentContainer}>
            <motion.p variants={textFadeUp("up", "spring", 0, 0.6)}
              initial="hidden"
              whileInView="show"
              viewport={{ once: true, amount: 0 }} className={`title ${styles.title}`}>Drive your business towards your goals and new opportunities.</motion.p>
            <motion.p variants={textFadeUp("up", "spring", .1, 0.6)}
              initial="hidden"
              whileInView="show"
              viewport={{ once: true, amount: 0 }} className={`subtitle ${styles.subtitle}`}>Access industry-leading technology strategy, design, and development for digital products and solutions.</motion.p>
          </div>
          <div className={styles.heroButtonWrapper}>
            <Link className="buttonPrimaryForeground buttonFullWidth" target="_top" href={`/contact`} >
              <span className={`callout`}>Schedule a call</span><Image height={12.87} width={12.87} src="clientActionArrowBlack.svg" priority alt=""></Image>
            </Link>
            <Link className="buttonSecondaryForeground buttonFullWidth" target="_top" href={`/contact`} >
              <span className={`callout`}>Message us</span><Image height={12.87} width={12.87} src="clientActionArrowWhite.svg" priority alt=""></Image>
            </Link>
          </div>
        </div>
      </div>

    </>
  )
}